<?php
/**
field =>       Adatbázis mező neve* title =>       Táblázat fejléce*
 * sortable =>    Rendezhető* switchable =>  Eltüntethető / Megjeleníthető. true / false* visible =>     Látható / Nem látható true / false* align =>       Jelölje meg, hogyan kell az oszlop adatait összehangolni. A 'left', 'right', 'center' használható.* halign =>      Jelölje meg, hogyan kell a táblázat fejlécét igazítani. A 'left', 'right', 'center' használható.* valign =>      Jelölje meg, hogyan kell összehangolni a cellaadatokat. 'top', 'middle', 'bottom' használható.* order =>       Az alapértelmezett rendezési sorrend csak 'asc' vagy 'desc' lehet.* formatter =>   Formázó függvény neve* */
return [
    'inv' => [
        [
            ['field' => 'operate',                  'title' => 'app.operations',                'align' => 'center','valign' => 'middle','clickToSelect' => false,'sortable' => false,'formatter' => 'operateFormatter','rowspan' => 2],
            ['field' => 'Inv_Num',                  'title' => 'inv.inv_num',                   'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => 'Inv_SeqNum',               'title' => 'inv.inv_seqnum',                'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => 'Partner_Name',             'title' => 'app.partner_name',              'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => 'InvType',                  'title' => 'app.type_of_invoice',           'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => 'PaymentMethod',            'title' => 'app.payment_method',            'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => 'PayStatus',                'title' => 'app.pay_status',                'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => '',                         'title' => 'inv.bank_and_tax_num',          'colspan' => 4,'align' => 'center','valign' => 'middle'],
            ['field' => '',                         'title' => 'app.lc',                        'colspan' => 5,'align' => 'right','valign' => 'middle'],
            ['field' => '',                         'title' => 'app.dc',                        'colspan' => 5,'align' => 'right','valign' => 'middle'],
            ['field' => '',                         'title' => 'app.fc',                        'colspan' => 5,'align' => 'right','valign' => 'middle'],
            ['field' => '',                         'title' => 'app.dates',                     'colspan' => 5,'align' => 'right','valign' => 'middle'],
            ['field' => 'Subcontracted_Services',   'title' => 'inv.subcontracted_services',    'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => '',                         'title' => 'app.partner_address',           'colspan' => 15,'align' => 'right','valign' => 'middle'],
            ['field' => '',                         'title' => 'inv.ACCT_Period',               'colspan' => 4,'align' => 'right','valign' => 'middle'],
            ['field' => 'Cancellation_ReasonCode',  'title' => 'inv.cancellation_reasoncode',   'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => 'Ref_Inv',                  'title' => 'inv.ref_inv',                   'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => 'Remarks',                  'title' => 'app.remarks',                   'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => 'Attachments',              'title' => 'app.attachments',               'rowspan' => 2,'align' => 'right','valign' => 'middle'],
            ['field' => 'Added_User_Name',          'title' => 'inv.added_user_name',           'rowspan' => 2,'align' => 'right','valign' => 'middle']
        ],
        [
            ['field' => 'Partner_Bank_Account', 'title' => 'Partner_Bank_Account',  'align' => '','valign' => ''],
            ['field' => 'Partner_Tax_Num',      'title' => 'Partner_Tax_Num',       'align' => '','valign' => ''],
            ['field' => 'Partner_Tax_Num2',     'title' => 'Partner_Tax_Num2',      'align' => '','valign' => ''],
            ['field' => 'Partner_IBAN',         'title' => 'Partner_IBAN',          'align' => '','valign' => ''],
            ['field' => 'Curr_LC',              'title' => 'app.curr',              'align' => '','valign' => ''],
            ['field' => 'Net_LC',               'title' => 'app.net',               'align' => '','valign' => ''],
            ['field' => 'Tax_LC',               'title' => 'app.tax',               'align' => '','valign' => ''],
            ['field' => 'Gross_LC',             'title' => 'app.gross',             'align' => '','valign' => ''],
            ['field' => 'PaidAmount_LC',        'title' => 'app.paid_amount',       'align' => '','valign' => ''],
            ['field' => 'Curr_DC',              'title' => 'app.curr',              'align' => '','valign' => ''],
            ['field' => 'Net_DC',               'title' => 'app.net',               'align' => '','valign' => ''],
            ['field' => 'Tax_DC',               'title' => 'app.tax',               'align' => '','valign' => ''],
            ['field' => 'Gross_DC',             'title' => 'app.gross',             'align' => '','valign' => ''],
            ['field' => 'PaidAmount_DC',        'title' => 'app.paid_amount',       'align' => '','valign' => ''],
            ['field' => 'Curr_FC',              'title' => 'app.curr',              'align' => '','valign' => ''],
            ['field' => 'Net_FC',               'title' => 'app.net',               'align' => '','valign' => ''],
            ['field' => 'Tax_FC',               'title' => 'app.tax',               'align' => '','valign' => ''],
            ['field' => 'Gross_FC',             'title' => 'app.gross',             'align' => '','valign' => ''],
            ['field' => 'PaidAmount_FC',        'title' => 'app.paid_amount',       'align' => '','valign' => ''],
            ['field' => 'InvDate',              'title' => 'inv.inv_date',          'align' => '','valign' => ''],
            ['field' => 'PostInDate',           'title' => 'inv.post_in_date',      'align' => '','valign' => ''],
            ['field' => 'DeliveryDate',         'title' => 'inv.delivery_date',     'align' => '','valign' => ''],
            ['field' => 'DueDate',              'title' => 'inv.due_date',          'align' => '','valign' => ''],
            ['field' => 'Fully_paid_date',      'title' => 'inv.fully_paid_date',   'align' => '','valign' => ''],
            ['field' => 'Partner_Full_Address', 'title' => 'inv.partner_full_address','align' => '','valign' => ''],
            ['field' => 'Partner_Country_State_ZIP_City',   'title' => 'inv.partner_country_state_zip_city','align' => '','valign' => ''],
            ['field' => 'Partner_Country',      'title' => 'inv.partner_country','align' => '','valign' => ''],
            ['field' => 'Partner_State',        'title' => 'inv.partner_state','align' => '','valign' => ''],
            ['field' => 'Partner_ZIP',          'title' => 'inv.partner_zip','align' => '','valign' => ''],
            ['field' => 'Partner_City',         'title' => 'inv.partner_city','align' => '','valign' => ''],
            ['field' => 'Partner_Addr_District','title' => 'inv.partner_addr_district','align' => '','valign' => ''],
            ['field' => 'Partner_Addr',         'title' => 'inv.partner_addr','align' => '','valign' => ''],
            ['field' => 'Partner_Addr_ps_type', 'title' => 'inv.partner_addr_ps_type','align' => '','valign' => ''],
            ['field' => 'Partner_District_PsType_HouseNr','title' => 'inv.partner_district_pstype_housenr','align' => '','valign' => ''],
            ['field' => 'Partner_Addr_housenr', 'title' => 'inv.partner_addr_housenr','align' => '','valign' => ''],
            ['field' => 'Partner_Addr_building','title' => 'inv.partner_addr_building','align' => '','valign' => ''],
            ['field' => 'Partner_Addr_stairway','title' => 'inv.partner_addr_stairway','align' => '','valign' => ''],
            ['field' => 'Partner_Addr_floor',   'title' => 'inv.partner_addr_floor','align' => '','valign' => ''],
            ['field' => 'Partner_Addr_door',    'title' => 'inv.partner_addr_door','align' => '','valign' => ''],
            ['field' => 'ACCT_Period',          'title' => 'inv.ACCT_Period','align' => '','valign' => ''],
            ['field' => 'Period_From_To',       'title' => 'inv.period_to_from','align' => '','valign' => ''],
            ['field' => 'Period_FROM',          'title' => 'inv.period_from','align' => '','valign' => ''],
            ['field' => 'Period_TO',            'title' => 'inv.period_to','align' => '','valign' => '']
        ]
    ],

    'inv_l' => [
        ['field' => 'Ord_Num',          'title' => 'inv_l.ord_num'],
        ['field' => 'PosInfo',          'title' => 'inv_l.pos_info'],
        ['field' => 'Rates_ID',         'title' => 'inv_l.rates_id'],
        ['field' => 'Descr',            'title' => 'app.descr'],
        ['field' => 'Note',             'title' => 'inv_l.note'],
        ['field' => 'Pcs',              'title' => 'app.pcs',                   'align' => 'right'],
        ['field' => 'Unit',             'title' => 'app.unit'],
        ['field' => 'UnitPrice_DC',     'title' => 'app.unit_price_dc',         'align' => 'right'],
        ['field' => 'Netto_DC',         'title' => 'app.net_dc',                'align' => 'right'],
        ['field' => 'ACCT_TaxCodes_ID', 'title' => 'inv_l.acct_tax_codes_id'],

        ['field' => 'TaxRate',          'title' => 'inv_l.tax_rate',            'align' => 'right'],
        ['field' => 'Tax_DC',           'title' => 'inv_l.tax_dc',              'align' => 'right'],
        ['field' => 'Gross_DC',         'title' => 'inv_l.gross_dc',            'align' => 'right'],
        ['field' => 'UnitPrice_FC2',    'title' => 'inv_l.unit_price_fc2',      'align' => 'right'],
        ['field' => 'Tax_FC2',          'title' => 'inv_l.tax_fc2',             'align' => 'right'],
        ['field' => 'Brutto_FC2',       'title' => 'inv_l.gross_fc2',           'align' => 'right'],
        ['field' => 'Curr_ID',          'title' => 'inv_l.curr_id'],
        ['field' => 'Period_From_To',   'title' => 'inv_l.period_from_to'],
        ['field' => 'Period_FROM',      'title' => 'inv_l.period_from'],
        ['field' => 'Period_TO',        'title' => 'inv_l.period_to'],
    ],

    'cp_wrhs_stocks' => array(
        array('field' => 'ID','title' => 'ID','align' => 'left','visible' => false,'switchable' => false,'group' => true,'sortable' => true,'sql_field' => 'ID',
        ),
        array('field' => 'ClientID','title' => 'ClientID','align' => 'right','visible' => false,'switchable' => false,'group' => true,'sortable' => true,'sql_field' => 'ClientID',
        ),
        array('field' => 'Cust_ID',                'title' => 'Cust_ID',               'align' => 'right', 'visible' => false, 'switchable' => false,                                      'group' => true, 'sortable' => true, 'sql_field' => 'Cust_ID',),
        array('field' => 'Stock_Date',             'title' => 'Stock_Date',            'align' => 'left',  'sortable' => true, 'sql_field' => 'Stock_Date',                                'group' => true, 'formatter' => 'dateFormatter',),
        array('field' => 'Items_No',               'title' => 'Items_No',              'align' => 'right', 'sortable' => true, 'sql_field' => 'Items_No',                                  'group' => true,),
        array('field' => 'Items_Description_1',    'title' => 'Items_Description_1',   'align' => 'left',  'sortable' => true, 'sql_field' => 'Items_Description_1',                       'group' => true,),
        array('field' => 'Items_Description_2',    'title' => 'Items_Description_2',   'align' => 'left',  'sortable' => true, 'sql_field' => 'Items_Description_2',                       'group' => true,),
        array('field' => 'Expire_Date',            'title' => 'Expire_Date',           'align' => 'left',  'sortable' => true, 'sql_field' => 'Expire_Date',                               'group' => true, 'formatter' => 'dateFormatter',),
        array('field' => 'Prod_Date',              'title' => 'Prod_Date',             'align' => 'left',  'sortable' => true, 'sql_field' => 'Prod_Date',                                 'group' => true, 'formatter' => 'dateFormatter',),
        array('field' => 'LOT_1',                  'title' => 'LOT_1',                 'align' => 'right', 'sortable' => true, 'sql_field' => 'LOT_1',                                     'group' => true,),
        array('field' => 'LOT_2',                  'title' => 'LOT_2',                 'align' => 'right', 'sortable' => true, 'sql_field' => 'LOT_2',                                     'group' => true,),
        array('field' => 'Warehouse',              'title' => 'Warehouse',             'align' => 'left',  'sortable' => true, 'sql_field' => 'Warehouse',                                 'group' => true,),
        array('field' => 'Location',               'title' => 'Location',              'align' => 'left',  'sortable' => true, 'sql_field' => 'Location',                                  'group' => true,),
        array('field' => 'Status',                 'title' => 'Status',                'align' => 'left',  'sortable' => true, 'sql_field' => 'Status',                                    'group' => true,),
        array('field' => 'Price_UnitPrice',        'title' => 'Price_UnitPrice',       'align' => 'right', 'sortable' => true, 'sql_field' => 'Price_UnitPrice',                           'group' => true, 'formatter' => 'decimalFormatter',),
        array('field' => 'Price_Currency',         'title' => 'Price_Currency',        'align' => 'left',  'sortable' => true, 'sql_field' => 'Price_Currency',                            'group' => true,),
        array('field' => 'Price_Unit',             'title' => 'Price_Unit',            'align' => 'left',  'sortable' => true, 'sql_field' => 'Price_Unit',                                'group' => true,),
        array('field' => 'Weight_Net',             'title' => 'Weight_Net',            'align' => 'right', 'sortable' => true, 'sql_field' => 'SUM(Weight_Net) Weight_Net',                'group' => false, 'formatter' => 'decimalFormatter',),
        array('field' => 'Weight_Gross',           'title' => 'Weight_Gross',          'align' => 'right', 'sortable' => true, 'sql_field' => 'SUM(Weight_Gross) Weight_Gross',            'group' => false, 'formatter' => 'decimalFormatter',),
        array('field' => 'Stock_Available',        'title' => 'Stock_Available',       'align' => 'left',  'sortable' => true, 'sql_field' => 'SUM(Stock_Available) Stock_Available',      'group' => false, 'formatter' => 'decimalFormatter',),
        array('field' => 'Stock_Reserved',         'title' => 'Stock_Reserved',        'align' => 'right', 'sortable' => true, 'sql_field' => 'SUM(Stock_Reserved) Stock_Reserved',        'group' => false, 'formatter' => 'decimalFormatter',),
        array('field' => 'Stock_External_1',       'title' => 'Stock_External_1',      'align' => 'right', 'sortable' => true, 'sql_field' => 'SUM(Stock_External_1) Stock_External_1',    'group' => false, 'formatter' => 'decimalFormatter',),
        array('field' => 'Stock_External_2',       'title' => 'Stock_External_2',      'align' => 'right', 'sortable' => true, 'sql_field' => 'SUM(Stock_External_2) Stock_External_2',    'group' => false, 'formatter' => 'decimalFormatter',),
        array('field' => 'Stock_External_3',       'title' => 'Stock_External_3',      'align' => 'right', 'sortable' => true, 'sql_field' => 'SUM(Stock_External_3) Stock_External_3',    'group' => false, 'formatter' => 'decimalFormatter',),
    ),
    'cp_wrhs_trans' => array(
        array('field' => 'ID',                          'title' => 'ID',                            'align' => 'right', 'visible' => false, 'switchable' => false, 'sortable' => true, 'sql_field' => 'ID',                            'group' => true),
        array('field' => 'ClientID',                    'title' => 'ClientID',                      'align' => 'right', 'visible' => false, 'switchable' => false, 'sortable' => true, 'sql_field' => 'ClientID',                      'group' => true),
        array('field' => 'Cust_ID',                     'title' => 'Cust_ID',                       'align' => 'right', 'visible' => false, 'switchable' => false, 'sortable' => true, 'sql_field' => 'Cust_ID',                       'group' => true),
        array('field' => 'SELEXPED_WRHS_TRANS_ID',      'title' => 'SELEXPED_WRHS_TRANS_ID',        'align' => 'right', 'sortable' => true, 'sql_field' => 'SELEXPED_WRHS_TRANS_ID',        'group' => true),
        array('field' => 'TransactID',                  'title' => 'TransactID',                    'align' => 'right', 'sortable' => true, 'sql_field' => 'TransactID',                    'group' => true),
        array('field' => 'Movement_No',                 'title' => 'Movement_No',                   'align' => 'right', 'sortable' => true, 'sql_field' => 'Movement_No',                   'group' => true),
        array('field' => 'Movement_Type',               'title' => 'Movement_Type',                 'align' => 'right', 'sortable' => true, 'sql_field' => 'Movement_Type',                 'group' => true),
        array('field' => 'Booking_Date',                'title' => 'Booking_Date',                  'align' => 'right', 'sortable' => true, 'sql_field' => 'Booking_Date',                  'group' => true, 'formatter' => 'dateFormatter',),
        array('field' => 'DeliveryDate',                'title' => 'DeliveryDate',                  'align' => 'right', 'sortable' => true, 'sql_field' => 'DeliveryDate',                  'group' => true, 'formatter' => 'dateFormatter',),
        array('field' => 'Deadline',                    'title' => 'Deadline',                      'align' => 'right', 'sortable' => true, 'sql_field' => 'Deadline',                      'group' => true, 'formatter' => 'dateFormatter',),
        array('field' => 'Customs_Clearance_Date',      'title' => 'Customs_Clearance_Date',        'align' => 'right', 'sortable' => true, 'sql_field' => 'Customs_Clearance_Date',        'group' => true, 'formatter' => 'dateFormatter',),
        array('field' => 'DeliveryNote_No',             'title' => 'DeliveryNote_No',               'align' => 'right', 'sortable' => true, 'sql_field' => 'DeliveryNote_No',               'group' => true),
        array('field' => 'Cont_Num',                    'title' => 'Cont_Num',                      'align' => 'right', 'sortable' => true, 'sql_field' => 'Cont_Num',                      'group' => true),
        array('field' => 'Plate_No',                    'title' => 'Plate_No',                      'align' => 'right', 'sortable' => true, 'sql_field' => 'Plate_No',                      'group' => true),
        array('field' => 'Status',                      'title' => 'Status',                        'align' => 'right', 'sortable' => true, 'sql_field' => 'Status',                        'group' => true),
        array('field' => 'Response_User_Name',          'title' => 'Response_User_Name',            'align' => 'right', 'sortable' => true, 'sql_field' => 'Response_User_Name',            'group' => true),
        array('field' => 'Response_User_Email',         'title' => 'Response_User_Email',           'align' => 'right', 'sortable' => true, 'sql_field' => 'Response_User_Email',           'group' => true),
        array('field' => 'Response_User_Phone',         'title' => 'Response_User_Phone',           'align' => 'right', 'sortable' => true, 'sql_field' => 'Response_User_Phone',           'group' => true),
        array('field' => 'Remarks_1',                   'title' => 'Remarks_1',                     'align' => 'right', 'sortable' => true, 'sql_field' => 'Remarks_1',                     'group' => true),
        array('field' => 'Remarks_2',                   'title' => 'Remarks_2',                     'align' => 'right', 'sortable' => true, 'sql_field' => 'Remarks_2',                     'group' => true),
        array('field' => 'External_Movement_No',        'title' => 'External_Movement_No',          'align' => 'right', 'sortable' => true, 'sql_field' => 'External_Movement_No',          'group' => true),
        array('field' => 'External_Transport_Order_No', 'title' => 'External_Transport_Order_No',   'align' => 'right', 'sortable' => true, 'sql_field' => 'External_Transport_Order_No',   'group' => true),
        array('field' => 'External_PO_No',              'title' => 'External_PO_No',                'align' => 'right', 'sortable' => true, 'sql_field' => 'External_PO_No',                'group' => true),
        array('field' => 'External_DeliveryNote_No',    'title' => 'External_DeliveryNote_No',      'align' => 'right', 'sortable' => true, 'sql_field' => 'External_DeliveryNote_No',      'group' => true),
    ),
    'cp_wrhs_trans_l' => array(
        array('field' => 'ID',                              'title' => 'ID',                                'align' => 'right', 'sortable' => true, 'sql_field' => 'ID',                                'group' => true,    'visible' => false, 'switchable' => false, ),
        array('field' => 'SELEXPED_WRHS_TRANS_L_ID',        'title' => 'SELEXPED_WRHS_TRANS_L_ID',          'align' => 'right', 'sortable' => true, 'sql_field' => 'SELEXPED_WRHS_TRANS_L_ID',          'group' => true),
        array('field' => 'SELEXPED_WRHS_TRANS_ID',          'title' => 'SELEXPED_WRHS_TRANS_ID',            'align' => 'right', 'sortable' => true, 'sql_field' => 'SELEXPED_WRHS_TRANS_ID',            'group' => true),
        array('field' => 'CP_WRHS_TRANS_ID',                'title' => 'CP_WRHS_TRANS_ID',                  'align' => 'right', 'sortable' => true, 'sql_field' => 'CP_WRHS_TRANS_ID',                  'group' => true),
        array('field' => 'Line_SeqNum',                     'title' => 'Line_SeqNum',                       'align' => 'right', 'sortable' => true, 'sql_field' => 'Line_SeqNum',                       'group' => true),
        array('field' => 'Items_No',                        'title' => 'Items_No',                          'align' => 'right', 'sortable' => true, 'sql_field' => 'Items_No',                          'group' => true),
        array('field' => 'Items_Description_1',             'title' => 'Items_Description_1',               'align' => 'right', 'sortable' => true, 'sql_field' => 'Items_Description_1',               'group' => true),
        array('field' => 'Items_Description_2',             'title' => 'Items_Description_2',               'align' => 'right', 'sortable' => true, 'sql_field' => 'Items_Description_2',               'group' => true),
        array('field' => 'Transport_ORD_OrderNum',          'title' => 'Transport_ORD_OrderNum',            'align' => 'right', 'sortable' => true, 'sql_field' => 'Transport_ORD_OrderNum',            'group' => true),
        array('field' => 'Qty',                             'title' => 'Qty',                               'align' => 'right', 'sortable' => true, 'sql_field' => 'Qty',                               'group' => true),
        array('field' => 'Expire_Date',                     'title' => 'Expire_Date',                       'align' => 'right', 'sortable' => true, 'sql_field' => 'Expire_Date',                       'group' => true),
        array('field' => 'Prod_Date',                       'title' => 'Prod_Date',                         'align' => 'right', 'sortable' => true, 'sql_field' => 'Prod_Date',                         'group' => true),
        array('field' => 'LOT_1',                           'title' => 'LOT_1',                             'align' => 'right', 'sortable' => true, 'sql_field' => 'LOT_1',                             'group' => true),
        array('field' => 'LOT_2',                           'title' => 'LOT_2',                             'align' => 'right', 'sortable' => true, 'sql_field' => 'LOT_2',                             'group' => true),
        array('field' => 'Volume',                          'title' => 'Volume',                            'align' => 'right', 'sortable' => true, 'sql_field' => 'Volume',                            'group' => true),
        array('field' => 'Footprint',                       'title' => 'Footprint',                         'align' => 'right', 'sortable' => true, 'sql_field' => 'Footprint',                         'group' => true),
        array('field' => 'Weight_Net',                      'title' => 'Weight_Net',                        'align' => 'right', 'sortable' => true, 'sql_field' => 'Weight_Net',                        'group' => true),
        array('field' => 'Weight_Gross',                    'title' => 'Weight_Gross',                      'align' => 'right', 'sortable' => true, 'sql_field' => 'Weight_Gross',                      'group' => true),
        array('field' => 'FROM_Warehouse',                  'title' => 'FROM_Warehouse',                    'align' => 'right', 'sortable' => true, 'sql_field' => 'FROM_Warehouse',                    'group' => true),
        array('field' => 'FROM_Location',                   'title' => 'FROM_Location',                     'align' => 'right', 'sortable' => true, 'sql_field' => 'FROM_Location',                     'group' => true),
        array('field' => 'FROM_Status',                     'title' => 'FROM_Status',                       'align' => 'right', 'sortable' => true, 'sql_field' => 'FROM_Status',                       'group' => true),
        array('field' => 'TO_Warehouse',                    'title' => 'TO_Warehouse',                      'align' => 'right', 'sortable' => true, 'sql_field' => 'TO_Warehouse',                      'group' => true),
        array('field' => 'TO_Location',                     'title' => 'TO_Location',                       'align' => 'right', 'sortable' => true, 'sql_field' => 'TO_Location',                       'group' => true),
        array('field' => 'TO_Status',                       'title' => 'TO_Status',                         'align' => 'right', 'sortable' => true, 'sql_field' => 'TO_Status',                         'group' => true),
        array('field' => 'Line_Price_UnitPrice',            'title' => 'Line_Price_UnitPrice',              'align' => 'right', 'sortable' => true, 'sql_field' => 'Line_Price_UnitPrice',              'group' => true),
        array('field' => 'Line_Price_Currency',             'title' => 'Line_Price_Currency',               'align' => 'right', 'sortable' => true, 'sql_field' => 'Line_Price_Currency',               'group' => true),
        array('field' => 'Line_Price_Unit',                 'title' => 'Line_Price_Unit',                   'align' => 'right', 'sortable' => true, 'sql_field' => 'Line_Price_Unit',                   'group' => true),
        array('field' => 'Line_Price_Net',                  'title' => 'Line_Price_Net',                    'align' => 'right', 'sortable' => true, 'sql_field' => 'Line_Price_Net',                    'group' => true),
        array('field' => 'Line_Price_VAT',                  'title' => 'Line_Price_VAT',                    'align' => 'right', 'sortable' => true, 'sql_field' => 'Line_Price_VAT',                    'group' => true),
        array('field' => 'Line_Price_Gross',                'title' => 'Line_Price_Gross',                  'align' => 'right', 'sortable' => true, 'sql_field' => 'Line_Price_Gross',                  'group' => true),
        array('field' => 'External_MarksAndNumbers_01',     'title' => 'External_MarksAndNumbers_01',       'align' => 'right', 'sortable' => true, 'sql_field' => 'External_MarksAndNumbers_01',       'group' => true),
        array('field' => 'External_MarksAndNumbers_02',     'title' => 'External_MarksAndNumbers_02',       'align' => 'right', 'sortable' => true, 'sql_field' => 'External_MarksAndNumbers_02',       'group' => true),
        array('field' => 'External_MarksAndNumbers_03',     'title' => 'External_MarksAndNumbers_03',       'align' => 'right', 'sortable' => true, 'sql_field' => 'External_MarksAndNumbers_03',       'group' => true),
        array('field' => 'Barcode_Picking_Pallet',          'title' => 'Barcode_Picking_Pallet',            'align' => 'right', 'sortable' => true, 'sql_field' => 'Barcode_Picking_Pallet',            'group' => true),
        array('field' => 'Barcode_Picking_Box',             'title' => 'Barcode_Picking_Box',               'align' => 'right', 'sortable' => true, 'sql_field' => 'Barcode_Picking_Box',               'group' => true),
        array('field' => 'Barcode_Item',                    'title' => 'Barcode_Item',                      'align' => 'right', 'sortable' => true, 'sql_field' => 'Barcode_Item',                      'group' => true),
        array('field' => 'Stock_Available_After_Movement',  'title' => 'Stock_Available_After_Movement',    'align' => 'right', 'sortable' => true, 'sql_field' => 'Stock_Available_After_Movement',    'group' => true),
        array('field' => 'Stock_Reserved_After_Movement',   'title' => 'Stock_Reserved_After_Movement',     'align' => 'right', 'sortable' => true, 'sql_field' => 'Stock_Reserved_After_Movement',     'group' => true),
        array('field' => 'Stock_External_1_After_Movement', 'title' => 'Stock_External_1_After_Movement',   'align' => 'right', 'sortable' => true, 'sql_field' => 'Stock_External_1_After_Movement',   'group' => true),
        array('field' => 'Stock_External_2_After_Movement', 'title' => 'Stock_External_2_After_Movement',   'align' => 'right', 'sortable' => true, 'sql_field' => 'Stock_External_2_After_Movement',   'group' => true),
        array('field' => 'Stock_External_3_After_Movement', 'title' => 'Stock_External_3_After_Movement',   'align' => 'right', 'sortable' => true, 'sql_field' => 'Stock_External_3_After_Movement',   'group' => true),
    ),
];
